export const ActionTypes = {
  SET_ALL_MOVIES: "SET_ALL_MOVIES",
  SET_DISPLAY_MOVIES: "SET_DISPLAY_MOVIES",
  SELECTED_MOVIE: "SELECTED_MOVIE",
  REMOVE_SELECTED_MOVIE: "REMOVE_SELECTED_MOVIE",
  SEARCH_MOVIE: "SEARCH_MOVIE",
  TOGGLE_AUTH_MODAL: "TOGGLE_AUTH_MODAL",
  TOGGLE_SELECT_SEAT: "TOGGLE_SELECT_SEAT",
  SET_SEAT_CONFIG: "SET_SEAT_CONFIG",
  ADD_SEAT:"ADD_SEAT",
  REMOVE_SEAT: "REMOVE_SEAT",
  UPDATE_TICKET_DETAILS: "UPDATE_TICKET_DETAILS",
  UPDATE_LOGIN_DATA: "UPDATE_LOGIN_DATA",
  UPDATE_LOCATION: "UPDATE_USER_LOCATION"
};
